# Generated by Django 3.2 on 2021-04-24 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 11, 17, 41, 319466, tzinfo=utc)),
        ),
    ]
