# Generated by Django 3.2 on 2021-04-24 11:25

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0005_auto_20210424_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='places',
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 11, 25, 55, 490974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='dests',
            field=models.CharField(default='', help_text='Please add Places as Comma Seprated', max_length=300, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
