# Generated by Django 3.2 on 2021-04-24 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0006_auto_20210424_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 12, 15, 3, 897938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='dests',
            field=models.CharField(default='', help_text='Please add Places as Comma Seprated', max_length=300),
        ),
    ]
