# Generated by Django 3.2 on 2021-04-25 03:33

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0008_auto_20210424_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_itinerary',
            name='title',
        ),
        migrations.AddField(
            model_name='tour_itinerary',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tour_itinerary',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='Nearest_nature_place',
            field=models.CharField(choices=[('Mountain', 'Mountain'), ('Beach', 'Beach'), ('City', 'City')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 3, 33, 13, 461171, tzinfo=utc)),
        ),
    ]
