# Generated by Django 3.2 on 2021-04-25 03:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0009_auto_20210425_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_itinerary',
            name='day_no',
        ),
        migrations.AddField(
            model_name='tour_package',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour_package',
            name='max_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 3, 42, 3, 535772, tzinfo=utc)),
        ),
    ]
