# Generated by Django 3.2 on 2021-04-25 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0010_auto_20210425_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('place', models.CharField(choices=[('Mountain', 'Mountain'), ('Beach', 'Beach'), ('City', 'City')], max_length=20)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='tour_package',
            name='places',
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 5, 45, 31, 711003, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Tour_place_hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(default=' ', max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour_app.hotel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour_app.tour_package')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bed_details', models.CharField(max_length=30)),
                ('capacity', models.CharField(max_length=30)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour_app.hotel')),
            ],
        ),
    ]
