# Generated by Django 3.2 on 2021-04-25 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0011_auto_20210425_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='place',
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 5, 59, 46, 14371, tzinfo=utc)),
        ),
    ]
