# Generated by Django 3.2 on 2021-04-25 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0012_auto_20210425_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_place_hotel',
            name='place_image',
            field=models.ImageField(default='/static/images/destination-8.jpg', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 7, 28, 28, 497976, tzinfo=utc)),
        ),
    ]
