# Generated by Django 3.2 on 2021-04-26 05:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0015_auto_20210426_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 5, 44, 9, 782919, tzinfo=utc)),
        ),
    ]
