# Generated by Django 3.2 on 2021-04-26 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0016_alter_tour_package_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 6, 25, 54, 295811, tzinfo=utc)),
        ),
    ]
