# Generated by Django 3.2 on 2021-04-26 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0017_alter_tour_package_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_package',
            name='cost_per_person',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 7, 58, 42, 37028, tzinfo=utc)),
        ),
    ]
