# Generated by Django 3.2 on 2021-04-27 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0019_alter_tour_package_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_itinerary',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 5, 11, 48, 867830, tzinfo=utc)),
        ),
    ]
