# Generated by Django 3.2 on 2021-04-27 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0020_auto_20210427_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_package',
            name='departure',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 8, 3, 2, 660224, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Tour_Inquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_date', models.DateField()),
                ('interested_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('people', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Tour_app.tour_package')),
            ],
        ),
    ]
