# Generated by Django 3.2 on 2021-04-30 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0024_auto_20210428_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='checkin_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hotel',
            name='checkout_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
