# Generated by Django 3.2 on 2021-04-30 08:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0025_auto_20210430_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Air Conditioning', 'Air Conditioning'), ('Free Wi-Fi', 'Free Wi-Fi'), ('Restaurant/Coffee Shop', 'Restaurant/Coffee Shop'), ('CCTV', 'CCTV'), ('Room Service', 'Room Service'), ('Swimming Pool', 'Swimming Pool')], default=' ', max_length=82),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
