# Generated by Django 3.2 on 2021-04-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0026_auto_20210430_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='no_of_available',
            field=models.IntegerField(default=10),
        ),
    ]
