# Generated by Django 3.2 on 2021-05-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_app', '0028_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='no_of_available',
        ),
        migrations.AddField(
            model_name='room',
            name='room_no',
            field=models.CharField(default='', max_length=500),
        ),
    ]
